# Configurações do datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.output.ansi.enabled=always

# Configuração do servidor
server.port=8080

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key